title: Kavita Chauhan
description: iOS Developer · Building Clean & Scalable Apps

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme

minimal_mistakes_skin: default

# Site Settings
name: Kavita Chauhan
author: Kavita Chauhan

# Navigation
nav:
  - title: "Projects"
    url: /projects/
  - title: "Experience"
    url: /experience/
  - title: "Skills"
    url: /skills/
